version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:1.16.0
    depends_on:
      - php
    ports:
      - '80:80'
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./laravel:/var/www/html
      - ./docker/php/tmp:/tmp
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ~/.composer/auth.json:/composer/auth.json
    working_dir: /var/www/html

  mysql:
    container_name: mysql
    image: mysql:5.7.26
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - /var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: local_db
      MYSQL_USER: local_db
      MYSQL_PASSWORD: password
